server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

bank.simulator.url=http://localhost:8080/payments

certificate.vault.secretkey=w5m+J8zR3pQy/6fL4K9u2vB1xS7N0gM4hA5lX8jK3nI=